### ISSUE TITLE
TS26 - Dívidas da R2

### ISSUE THREAD

**Issue by mksgalvao** [fga-gpp-mds/fisCAE-2017-2#117]
**eu como** desenvolvedor
**desejo** implementar as dívidas de histórias da R2
**para que** possa entregar um produto que atenda os requisitos do cliente 

**task**

- [ ] Enviar os dados para a nuvem cívica.
- [ ] tornar as consultas às legislações e cartilha mais interativas.
- [ ] associar um mapa às respectivas escolas.
- [ ] consultar as informações das escolas.
- [ ] Aumentar a cobertura de teste da aplicação. 
- [ ] Refatorar frontend e torná-lo responsivo.
