### ISSUE TITLE
TS27 - Refatorar bugs da R2

### ISSUE THREAD

**Issue by mksgalvao** [fga-gpp-mds/fisCAE-2017-2#118]
**eu como** desenvolvedor
**desejo** fazer melhorias nas histórias implementadas na R2
**para que** possa entregar um produto sem bugs e funcionando integralmente.
**task**

- [ ] Mostrar as imagens salvas no checklist.
- [ ] Mandar email de notificação ao editar reunião ou visita.
- [ ] Salvar arquivos de imagens e documentos em pastas diferentes.
- [ ] Mandar email de notificação ao cadastrar um novo presidente ou aceitar cadastro de conselheiro.
 -[ ] Dar oportunidade de escolher um órgão específico ao fazer a denúncia. 
- [ ] Fazer a integração com a nuvem cívica para mandar todos os dados coletados. 
- [ ] Aumentar a cobertura de teste da aplicação. 
- [ ] Refatorar frontend e torná-lo responsivo.
