### ISSUE TITLE
TS02 - Refatorar Checklist

### ISSUE THREAD

**Issue by oliveiraMarcelo** [fga-gpp-mds/fisCAE-2017-2#26]
**Eu como** Usuário
**Desejo** ter acesso aos checklists
**Para que** Para que possa preenchê-los e enviá-los e, assim, possuir dados suficientes para a elaboração do relatório

Task:
- [ ] Apresentar categorizadas questões e checklists
- [ ] Autenticar acesso aos checklists, questões e respostas

Critérios de avaliação:
- [ ] Acessar formulário de checklist
- [ ] Salvar checklist corretamente no banco de dados
- [ ] Acessar questões de um checklist específico
- [ ] Salvar corretamente as respostas das questões no banco de dados
