### ISSUE TITLE
US12 - Nuvem Cívica

### ISSUE THREAD

**Issue by henriquedutra** [fga-gpp-mds/fisCAE-2017-2#45]
**Eu como** desenvolvedor
**Desejo** vincular a arquitetura do sistema FisCAE a nuvem cívica do TCU
**Para que** possa integrar os dados entre a nuvem e o FisCAE

**Tasks**
- [ ] Criar funcionalidades para autenticar usuário na nuvem cívica
- [ ] Criar funcionalidades para registrar perfis de usuários na nuvem
- [ ] Criar funcionalidades para associar usuários à perfis
