### ISSUE TITLE
TS17- Adicionar nome do CAE ao registro

### ISSUE THREAD

**Issue by aquiles23** [fga-gpp-mds/fisCAE-2017-2#74]
**eu como**  desenvolvedor
**desejo** inserir um campo "A qual CAE o usuário pertence" ao registro
**para que**  possa identificar quais usuários pertencem a cada CAE e assim direcionar os conteúdos dos mesmos. 

**tasks**

- [ ] Receber e validar a entrada do usuário
- [ ] aplicar os testes
- [ ] separar os eventos de acordo com CAEs
